// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Point struct {
	Lat string `json:"lat"`
	Lng string `json:"lng"`
}

type State struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Colour string   `json:"colour"`
	Points []*Point `json:"points"`
}
